### ISSUE TITLE
Values in peaks tables show up twice

### ISSUE THREAD

**Issue by larnsce** [Global-Health-Engineering/manuscript-hospital-air-quality#5]
![Screenshot 2022-06-07 at 10 52 07](https://user-images.githubusercontent.com/18212549/172339032-0ca72615-92d1-4383-bc25-aa20e347d181.png)

Submitted by @elizabeth-tilley

**Comment by elizabeth-tilley** [comment]
whoa but now these values are totally different

**Comment by larnsce** [comment]
The screenshot above is the version that wasn't fixed yet.

It's done now:

https://github.com/Global-Health-Engineering/manuscript-hospital-air-quality#table-peaks-over-the-limit-for-hazardous-world-health-organization-2021
